Use DonutShop

CREATE TABLE Flavours(
	FlavourID INT PRIMARY KEY,
	Name VARCHAR(20)
)

DROP TABLE Flavours

CREATE TABLE Donuts(
	DonutID INT PRIMARY KEY,
	Name VARCHAR(50),
	Stock INT,
	Price FLOAT,
	Flavour INT FOREIGN KEY REFERENCES Flavours(FlavourID) ON DELETE CASCADE
)

DROP TABLE Donuts

CREATE TABLE Boxes(
	BoxID INT PRIMARY KEY,
	Name VARCHAR(50)
)

DROP TABLE Boxes

CREATE TABLE DonutsBoxes(
	dbID INT PRIMARY KEY,
	BoxID INT FOREIGN KEY REFERENCES Boxes(BoxID) ON DELETE CASCADE,
	DonutID INT FOREIGN KEY REFERENCES Donuts(DonutID) ON DELETE CASCADE
)

DROP TABLE DonutsBoxes

CREATE TABLE Clients(
	ClientID INT PRIMARY KEY,
	Name VARCHAR(100),
	Phone VARCHAR(15),
	Address VARCHAR(100)
)

DROP TABLE Clients

CREATE TABLE Aquisitions
(
	AqID INT PRIMARY KEY,
	ClientID INT FOREIGN KEY REFERENCES Clients(ClientID) ON DELETE CASCADE,
	BoxID INT FOREIGN KEY REFERENCES Boxes(BoxID) ON DELETE CASCADE,
	Opt VARCHAR(10)
)

DROP TABLE Aquisitions